version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      pkLBV1FTYAaozSwOAIT3uNoMbuj2wWhBENOSkSCe3Jrl8k8Ipm8gzRY1pSUyeQwDDPp3bLEoMSrTKsTvU0caqH1d2Z2l5ItUvRprsftOAnXeVeESwojTmCzzJJ2F1I0utqp+sFaWFW1NlqALbPZ6T14SOpC05F9BcFmPf0c9R8BxNTztRDjRJyBDpEiDRGsvJ/X6615x+znK6641xAy9zf+Ocy2Sl8VTzeSvKbORAEY8enB+/xt3oTSMqCvTLLEvuO7ae6XRBtkUbuk1WZ1nzzS74uDhVSgkVHHAzJmXlRHMyVOgihnWP8hO6czQIQQnXC02ZJCMf3eeC/zj6Mo8c5C8UQ16ijfhK9lrfu9o+MPXr8McKB5zYEFz72364ZIe3qLyrSATjhYP+hGFjVHVGxdQuFX9oWrtX8EtAIe+O5jafSMwK8YAPThGh5cYWBcw5cgCk1Ceh8kWG2LbJE4d8Ck1BAbPxsTT6mvhb1Bth8MCmfLZh7Mhajr2gWJRYoMFHip0AtF3sNqGUhDw7GH595y6sMK8pka9nJANQlYxS8A1MjnhLG7feNl7rwQ5wgg3TVlaJqAOOdYMqrfqxRh+5FE0vUJiNMduzwpRj8IjuerjOmNaxKxcXXO5b2aQRKs0W6uCl+vciRNU/JlP64FziqimxNQRGmDxD2fGF4IUVLg=
