sudo: false
language: node_js
node_js:
- '0.8'
- '0.10'
- '0.12'
- '4'
- '6'
- '8'
- '10'
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '0.8'
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffa/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffa/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffa/scripts/surge.bash)"
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/a16fffa/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: L4OCn10RDqRDSSgnOoYbUOvVQxpOfkiyrbzlbGueMyZGU7g7Pino+ZTQU/m7Z2j97B068iHerbvQukPbR1KJ9bTT8R3aWNdXIBL+KDnpYpBTDTMor0djN0e6N4JLVIvtOVfFyhc8Q3DP8YA+VbgwoYngy8acupPwKM2Bg1PEG+JE9tWWbMLY7UNSQavQ2J7SMnY16h1EIBGtAodrjCtku3Lx3eZmUlURFKVK1mPkgNar1gc+PMBv/fzRQOSHQxVwD7AI+N6JEIBuYkRI30l798b/jzwZHerjcj+O3vMH6DlhW+FtTibN1IYKIgwu7/bY8Tm9T0g38VbNAwPRXsdGlFXJYQrxybCol2PASAA6rFks4NXmvLevlHXYy6U42+QuoNK3NgWMAAE+8rIIpz2bfmK92jglZBRRW628JUMwgl0UviugY89kAOt9H4633oTOeNZ+/rWxa0HPis2hmM2bvtJNNjdO6F8YU3ZennskP0tjVH0S36BjkrpynQeDQkyoLgqJqCzwSVm+whvkmqIhfjnyonKDf4nit5iiJc0WS7H/sroNycvBO9IszRHr+9xr60fZwI97MzPX6/grQFSG2PpT4tkYz4Nfpi3GLaIRNjAo7ZrI/Z1v8pMFc+6dYkTEYpn0jHUs6oFIgURvuGhhl6aW4iY8n7isa70jfM2Svxg=
