version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      j+Jad3RQwXJOB+Isq2nQOrHgPBcvl5JRWkSQVW0pkARF/MayRodJd7+Vmef3vMQRy6AOFeW3HJGYfZS+cpvo+yr0fA+tGfsQzF2jaosQr0imtz9Vxk6lLHTV+g4AwFHKqQDhI84MupZVWK2D0VzScWF2CHRkCQKyudT3NUSC1tlM66oLAw0uCnrArcYzmpBOQz7DCNn5YKvQmqZmsGXxNruLPQOkGZXz17z17XdNqArW9pZ7fVlS1kwIgwcZfReXbvLepSzgxB87TjhG9TGT0ROo8HCcVAezOsaMdcQ3tko6k7B0Vb/vCYW/pb/NM5RnM98bGzU7EbPFCXITQD5ejMBIjyYrzWjmDbSULQChp4+Llout2TjIm0iHDbJj0D4iXDamdTZzG2xf5UNc7KbRUOHZhBUbJqzc2Iw6lp5rYJZO4qOe/FkupIM6af1D8sKOrhPHlVlUKXQjLzAjARZvMwjXANrC+760yZvRlB6ma20p8j8syFXtjdUGciNjP2r2mNl61b/SVWa++uLhJ6vfwV/SIP10DdnTnwSec8g8vQexxt+Xnfjnme427zC+IisSOpp989ExwRDh0wWw4vDgFiZguJ1z59BXXkY54qP2fVT58vZoKO3kEAFKYx9gbte5dd4Jfow1YIIBB4yUJxQKd8nq/m3Vxm8CdptxyNrH01A=
